### PR TITLE
Getrelease fixes and updated example list of tarballs/sets

### LINKED ISSUE #6: getrelease is broken
I tried to update today:

```
[ec2-user@aws-1 ~/src/mkjail]$ sudo ./src/bin/mkjail getrelease -s base -v 12.2-RELEASE
Both -s and -v must be specified.

usage: mkjail getrelease [-s "SETS"] [-v VERSION]

        -s Sets: "base doc games lib32"
        -v Version of jail (9.3-RELEASE, 10.1-RELEASE, etc)

mkjail.sh: 2019, feld@FreeBSD.org

[ec2-user@aws-1 ~/src/mkjail]$ sudo ./src/bin/mkjail getrelease -v 12.2-RELEASE 
Both -s and -v must be specified.

usage: mkjail getrelease [-s "SETS"] [-v VERSION]

        -s Sets: "base doc games lib32"
        -v Version of jail (9.3-RELEASE, 10.1-RELEASE, etc)

mkjail.sh: 2019, feld@FreeBSD.org

[ec2-user@aws-1 ~/src/mkjail]$ sudo ./src/bin/mkjail getrelease -v 12.2-RELEASE  -s base
Both -s and -v must be specified.

usage: mkjail getrelease [-s "SETS"] [-v VERSION]

        -s Sets: "base doc games lib32"
        -v Version of jail (9.3-RELEASE, 10.1-RELEASE, etc)

mkjail.sh: 2019, feld@FreeBSD.org

[ec2-user@aws-1 ~/src/mkjail]$ 
```

### PR DESCRIPTION
**Pull request by feld**
Should fix #6

### CODE REVIEW

File: src/share/mkjail/getrelease.sh [hunk 1]
```diff
@@ -106,7 +106,7 @@ done
 
 shift $(($OPTIND - 1))
 
-if [ ${vflag} = 0 ]; then
+if [ ${vflag} -eq 0 ]; then
     exit_opts_req
```
Comment (dlangille) [inline src/share/mkjail/getrelease.sh:110]: Good set of catches here.

File: src/etc/mkjail.conf.sample [hunk 2]
```diff
@@ -7,5 +7,5 @@ ZPOOL="zroot"
 JAILROOT="/jails"
 
 # Sets you want extracted into new jail
-# options include: base, doc, games (deprecated), kernel, lib32, ports, src
+# options include: base-dbg, base, kernel-dbg, kernel, lib32-dbg, lib32, ports, src tests
 SETS="base lib32"
```
Comment (dlangille) [inline src/etc/mkjail.conf.sample:11]: Why not base, base-dbg?

**Review by dlangille — COMMENTED** [review]
I'm running an upgrade of two FreeBSD 13.0 jails now

**Comment by dlangille** [comment]
Oh, I see the jails are 12.2, the host is 13.0-RELEASE-p1 - good still though: now I can test `upgrade` as well.

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail update -a
Updating all jails...

Updating pg01 jail...

src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 12.2-RELEASE from update1.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata patches.. done.
Applying metadata patches... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 4 patches... done.
Applying patches... done.
The following files will be updated as part of updating to
12.2-RELEASE-p7:
/bin/freebsd-version
/usr/lib/libradius.a
/usr/lib/libradius.so.4
/usr/lib/libradius_p.a
Installing updates...Scanning /jails/pg01/usr/share/certs/blacklisted for certificates...
Scanning /jails/pg01/usr/share/certs/trusted for certificates...
Scanning /jails/pg01/usr/local/share/certs for certificates...
 done.

Updating ingress01 jail...

src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 12.2-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.
The following files will be updated as part of updating to
12.2-RELEASE-p7:
/bin/freebsd-version
/usr/lib/libradius.a
/usr/lib/libradius.so.4
/usr/lib/libradius_p.a
Installing updates...Scanning /jails/ingress01/usr/share/certs/blacklisted for certificates...
Scanning /jails/ingress01/usr/share/certs/trusted for certificates...
Scanning /jails/ingress01/usr/local/share/certs for certificates...
 done.

Updating nginx01 jail...

src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 12.2-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.
The following files will be updated as part of updating to
12.2-RELEASE-p7:
/bin/freebsd-version
/usr/lib/libradius.a
/usr/lib/libradius.so.4
/usr/lib/libradius_p.a
Installing updates...Scanning /jails/nginx01/usr/share/certs/blacklisted for certificates...
Scanning /jails/nginx01/usr/share/certs/trusted for certificates...
Scanning /jails/nginx01/usr/local/share/certs for certificates...
 done.

[dvl@r720-02:~/src/mkjail] $ 

```

**Comment by dlangille** [comment]
This seems correct:

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail upgrade -a
usage: mkjail upgrade [-a] [-v TARGETVER] | [-j JAILNAME] [-v TARGETVER]

        -a Upgrade all running jails
        -h Show help
        -j Jail name
        -v FreeBSD version (e.g., 11.1-RELEASE)

mkjail.sh: 2019, feld@FreeBSD.org

[dvl@r720-02:~/src/mkjail] $ 
```

**Comment by dlangille** [comment]
And then:

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail upgrade -a -v 13.0-RELEASE
cannot open 'zroot/mkjail': dataset does not exist
Missing required sets for 13.0-RELEASE.
Please run 'mkjail getrelease' for the version you want to upgrade to.
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail getrelease -v 13.0-RELEASE
Fetching release manifest...
MANIFEST                                              1046  B 7451 kBps    00s
Fetching release tarballs...
base.txz                                               180 MB   10 MBps    18s
src.txz                                                153 MB   10 MBps    14s
base.txz: sha256 verified
src.txz: sha256 verified
Extracting src for use in jail upgrades...
[dvl@r720-02:~/src/mkjail] $ 
```

The dataset was created:
```
[dvl@r720-02:~] $ zfs list -r zroot/mkjail
NAME                        USED  AVAIL     REFER  MOUNTPOINT
zroot/mkjail                702M  84.3G       96K  /zroot/mkjail
zroot/mkjail/13.0-RELEASE   702M  84.3G      702M  /zroot/mkjail/13.0-RELEASE
[dvl@r720-02:~] $ zfs get creation zroot/mkjail
NAME          PROPERTY  VALUE                  SOURCE
zroot/mkjail  creation  Fri May 28 18:44 2021  -
[dvl@r720-02:~] $ date
Fri May 28 18:46:05 UTC 2021
[dvl@r720-02:~] $ 
```

**Comment by dlangille** [comment]
But it still thinks it is not installed. I am looking into that now.

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail upgrade -a -v 13.0-RELEASE
Missing required sets for 13.0-RELEASE.
Please run 'mkjail getrelease' for the version you want to upgrade to.
[dvl@r720-02:~/src/mkjail] $ 
```

**Comment by dlangille** [comment]
```
[dvl@r720-02:~/src/mkjail] $ cat src/etc/mkjail.conf
# mkjail config file

# Set your zpool name
ZPOOL="zroot"

# Set jail root filesystem path
JAILROOT="/jails"

# Sets you want extracted into new jail
# options include: base, doc, games (deprecated), kernel, lib32, ports, src
SETS="base"
[dvl@r720-02:~/src/mkjail] $ 
```

**Comment by dlangille** [comment]
So, let's only check that we have set for which are are using, i.e. those in `SETS`

```
--- a/src/share/mkjail/upgrade.sh
+++ b/src/share/mkjail/upgrade.sh
@@ -83,9 +83,9 @@ _validate()
     export MKJAILVER="$(zfs get -H mkjail:version ${JAILROOT}/${JAILNAME} | awk '{print $3}')"
 
     # Check if we have the sets for the target version we are upgrading to
-    [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/base.txz ] || _getrelease
-    [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/lib32.txz ] || _getrelease
-    [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/src.txz ] || _getrelease
+    for DIST in $(echo "${SETS}"); do
+      [ -f /var/db/mkjail/releases/${ARCH}/${TARGETVER}/${DIST}.txz ]  || _getrelease
+    done
     [ -d ${SRCPATH} ] || _getrelease
 }
```

But that gives this error.  Perhaps we should do [this lib32.exe check](https://github.com/mkjail/mkjail/blob/master/src/share/mkjail/upgrade.sh#L36) sooner in this list?  Or verify that's in the `SETS`?

NOTE the failed attempt to `umount` the jails `usr/src`

I will proceed by adding `lib32` to `SETS` and rerunning `getrelease`.

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail upgrade -a -v 13.0-RELEASE
Upgrading pg01 jail from 12.2-RELEASE to 13.0-RELEASE...

tar: Error opening archive: Failed to open '/var/db/mkjail/releases/amd64/13.0-RELEASE/lib32.txz'

Upgrade cancelled: reverting changes and cleaning up.
umount: /jails/pg01/usr/src: not a file system root directory
[dvl@r720-02:~/src/mkjail] $ 

```

**Comment by dlangille** [comment]
```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail getrelease -v 13.0-RELEASE
Fetching release manifest...
MANIFEST                                              1046  B 7451 kBps    00s
Fetching release tarballs...
base.txz                                               180 MB   10 MBps    17s
lib32.txz                                               67 MB   11 MBps    06s
src.txz                                                153 MB   11 MBps    13s
base.txz: sha256 verified
lib32.txz: sha256 verified
src.txz: sha256 verified
Extracting src for use in jail upgrades...
[dvl@r720-02:~/src/mkjail] $ 
```

**Comment by dlangille** [comment]
This failure occurs because I have a custom repo, not the FreeBSD repo.

My solution: update via `sudoedit /jails/*/usr/local/etc/pkg/repos/local.conf` and run the script again. See next comment.

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail upgrade -a -v 13.0-RELEASE
Upgrading pg01 jail from 12.2-RELEASE to 13.0-RELEASE...

  D /etc/amd.map
  D /etc/newsyslog.conf.d/amd.conf
  D /etc/rc.d/amd
  D /etc/rc.d/nsswitch
  D /etc/rc.d/timed
  U /etc/auto_master
  U /etc/autofs/include_ldap
  U /etc/autofs/include_nis
  U /etc/autofs/include_nis_nullfs
  U /etc/autofs/special_hosts
  U /etc/autofs/special_media
  U /etc/autofs/special_noauto
  U /etc/autofs/special_null
  U /etc/blacklistd.conf
  U /etc/bluetooth/hcsecd.conf
  U /etc/bluetooth/hosts
  U /etc/bluetooth/protocols
  U /etc/cron.d/at
  U /etc/crontab
  U /etc/csh.cshrc
  U /etc/csh.login
  U /etc/csh.logout
  U /etc/ddb.conf
  U /etc/defaults/bluetooth.device.conf
  U /etc/defaults/devfs.rules
  U /etc/defaults/periodic.conf
  U /etc/defaults/rc.conf
  U /etc/devd.conf
  U /etc/devd/asus.conf
  U /etc/devd/devmatch.conf
  U /etc/devd/hyperv.conf
  U /etc/devd/iwmbtfw.conf
  U /etc/devd/uath.conf
  U /etc/devd/ulpt.conf
  U /etc/devd/zfs.conf
  U /etc/devfs.conf
  U /etc/dhclient.conf
  U /etc/disktab
  U /etc/dma/dma.conf
  U /etc/fbtab
  U /etc/freebsd-update.conf
  U /etc/ftpusers
  U /etc/gettytab
  M /etc/group
  U /etc/gss/mech
  U /etc/gss/qop
  U /etc/hosts.allow
  U /etc/hosts.equiv
  U /etc/hosts.lpd
  U /etc/inetd.conf
  U /etc/libalias.conf
  U /etc/libmap.conf
  U /etc/locate.rc
  U /etc/login.access
  U /etc/login.conf
  U /etc/mac.conf
  U /etc/mail/Makefile
  U /etc/mail/README
  U /etc/mail/access.sample
  M /etc/mail/aliases
  U /etc/mail/freebsd.cf
  U /etc/mail/freebsd.mc
  U /etc/mail/freebsd.submit.cf
  U /etc/mail/freebsd.submit.mc
  M /etc/mail/mailer.conf
  U /etc/mail/mailertable.sample
  U /etc/mail/sendmail.cf
  U /etc/mail/submit.cf
  U /etc/mail/virtusertable.sample
  M /etc/master.passwd
  U /etc/mtree/BSD.debug.dist
  U /etc/mtree/BSD.include.dist
  U /etc/mtree/BSD.lib32.dist
  U /etc/mtree/BSD.root.dist
  U /etc/mtree/BSD.sendmail.dist
  U /etc/mtree/BSD.tests.dist
  U /etc/mtree/BSD.usr.dist
  U /etc/mtree/BSD.var.dist
  U /etc/netconfig
  U /etc/netstart
  U /etc/network.subr
  U /etc/networks
  M /etc/newsyslog.conf
  U /etc/newsyslog.conf.d/ftp.conf
  U /etc/newsyslog.conf.d/lpr.conf
  U /etc/newsyslog.conf.d/opensm.conf
  U /etc/newsyslog.conf.d/pf.conf
  U /etc/newsyslog.conf.d/ppp.conf
  U /etc/newsyslog.conf.d/sendmail.conf
  U /etc/nscd.conf
  U /etc/nsmb.conf
  U /etc/nsswitch.conf
  U /etc/ntp.conf
  U /etc/opieaccess
  U /etc/pam.d/README
  U /etc/pam.d/atrun
  U /etc/pam.d/cron
  U /etc/pam.d/ftp
  U /etc/pam.d/imap
  U /etc/pam.d/login
  U /etc/pam.d/other
  U /etc/pam.d/passwd
  U /etc/pam.d/pop3
  U /etc/pam.d/sshd
  U /etc/pam.d/su
  U /etc/pam.d/system
  U /etc/pam.d/telnetd
  U /etc/pam.d/xdm
  U /etc/pccard_ether
  U /etc/periodic/daily/100.clean-disks
  U /etc/periodic/daily/110.clean-tmps
  U /etc/periodic/daily/120.clean-preserve
  U /etc/periodic/daily/130.clean-msgs
  U /etc/periodic/daily/140.clean-rwho
  U /etc/periodic/daily/150.clean-hoststat
  U /etc/periodic/daily/200.backup-passwd
  U /etc/periodic/daily/210.backup-aliases
  U /etc/periodic/daily/300.calendar
  U /etc/periodic/daily/310.accounting
  U /etc/periodic/daily/330.news
  U /etc/periodic/daily/400.status-disks
  U /etc/periodic/daily/401.status-graid
  U /etc/periodic/daily/404.status-zfs
  U /etc/periodic/daily/406.status-gmirror
  U /etc/periodic/daily/407.status-graid3
  U /etc/periodic/daily/408.status-gstripe
  U /etc/periodic/daily/409.status-gconcat
  U /etc/periodic/daily/410.status-mfi
  U /etc/periodic/daily/420.status-network
  U /etc/periodic/daily/430.status-uptime
  U /etc/periodic/daily/440.status-mailq
  U /etc/periodic/daily/450.status-security
  U /etc/periodic/daily/460.status-mail-rejects
  U /etc/periodic/daily/480.leapfile-ntpd
  U /etc/periodic/daily/480.status-ntpd
  U /etc/periodic/daily/500.queuerun
  U /etc/periodic/daily/510.status-world-kernel
  U /etc/periodic/daily/800.scrub-zfs
  U /etc/periodic/daily/999.local
  U /etc/periodic/monthly/200.accounting
  U /etc/periodic/monthly/450.status-security
  U /etc/periodic/monthly/999.local
  U /etc/periodic/security/100.chksetuid
  U /etc/periodic/security/110.neggrpperm
  U /etc/periodic/security/200.chkmounts
  U /etc/periodic/security/300.chkuid0
  U /etc/periodic/security/400.passwdless
  U /etc/periodic/security/410.logincheck
  U /etc/periodic/security/500.ipfwdenied
  U /etc/periodic/security/510.ipfdenied
  U /etc/periodic/security/520.pfdenied
  U /etc/periodic/security/550.ipfwlimit
  U /etc/periodic/security/610.ipf6denied
  U /etc/periodic/security/700.kernelmsg
  U /etc/periodic/security/800.loginfail
  U /etc/periodic/security/900.tcpwrap
  U /etc/periodic/security/security.functions
  U /etc/periodic/weekly/310.locate
  U /etc/periodic/weekly/320.whatis
  U /etc/periodic/weekly/340.noid
  U /etc/periodic/weekly/450.status-security
  U /etc/periodic/weekly/999.local
  U /etc/pf.os
  U /etc/phones
  U /etc/pkg/FreeBSD.conf
  U /etc/portsnap.conf
  U /etc/ppp/ppp.conf
  U /etc/printcap
  U /etc/profile
  U /etc/protocols
  U /etc/rc
  U /etc/rc.bsdextended
  U /etc/rc.d/DAEMON
  U /etc/rc.d/FILESYSTEMS
  U /etc/rc.d/LOGIN
  U /etc/rc.d/NETWORKING
  U /etc/rc.d/SERVERS
  U /etc/rc.d/accounting
  U /etc/rc.d/addswap
  U /etc/rc.d/adjkerntz
  U /etc/rc.d/apm
  U /etc/rc.d/archdep
  U /etc/rc.d/auditd
  U /etc/rc.d/auditdistd
  U /etc/rc.d/automount
  U /etc/rc.d/automountd
  U /etc/rc.d/autounmountd
  U /etc/rc.d/bgfsck
  U /etc/rc.d/blacklistd
  U /etc/rc.d/bluetooth
  U /etc/rc.d/bootparams
  U /etc/rc.d/bridge
  U /etc/rc.d/bsnmpd
  U /etc/rc.d/bthidd
  U /etc/rc.d/ccd
  U /etc/rc.d/cfumass
  U /etc/rc.d/cleanvar
  U /etc/rc.d/cleartmp
  U /etc/rc.d/cron
  U /etc/rc.d/ctld
  U /etc/rc.d/ddb
  U /etc/rc.d/defaultroute
  U /etc/rc.d/devd
  U /etc/rc.d/devfs
  U /etc/rc.d/devmatch
  U /etc/rc.d/dhclient
  U /etc/rc.d/dmesg
  U /etc/rc.d/dumpon
  U /etc/rc.d/fsck
  U /etc/rc.d/ftp-proxy
  U /etc/rc.d/ftpd
  U /etc/rc.d/gbde
  U /etc/rc.d/geli
  U /etc/rc.d/geli2
  U /etc/rc.d/gptboot
  U /etc/rc.d/growfs
  U /etc/rc.d/gssd
  U /etc/rc.d/hastd
  U /etc/rc.d/hcsecd
  U /etc/rc.d/hostapd
  U /etc/rc.d/hostid
  U /etc/rc.d/hostid_save
  U /etc/rc.d/hostname
  U /etc/rc.d/inetd
  U /etc/rc.d/iovctl
  U /etc/rc.d/ip6addrctl
  U /etc/rc.d/ipfilter
  U /etc/rc.d/ipfs
  U /etc/rc.d/ipfw
  U /etc/rc.d/ipfw_netflow
  U /etc/rc.d/ipmon
  U /etc/rc.d/ipnat
  U /etc/rc.d/ippool
  U /etc/rc.d/ipropd_master
  U /etc/rc.d/ipropd_slave
  U /etc/rc.d/ipsec
  U /etc/rc.d/iscsictl
  U /etc/rc.d/iscsid
  U /etc/rc.d/jail
  U /etc/rc.d/kadmind
  U /etc/rc.d/kdc
  U /etc/rc.d/keyserv
  U /etc/rc.d/kfd
  U /etc/rc.d/kld
  U /etc/rc.d/kldxref
  U /etc/rc.d/kpasswdd
  U /etc/rc.d/ldconfig
  U /etc/rc.d/linux
  U /etc/rc.d/local
  U /etc/rc.d/local_unbound
  U /etc/rc.d/localpkg
  U /etc/rc.d/lockd
  U /etc/rc.d/lpd
  U /etc/rc.d/mdconfig
  U /etc/rc.d/mdconfig2
  U /etc/rc.d/mixer
  U /etc/rc.d/motd
  U /etc/rc.d/mountcritlocal
  U /etc/rc.d/mountcritremote
  U /etc/rc.d/mountd
  U /etc/rc.d/mountlate
  U /etc/rc.d/moused
  U /etc/rc.d/msgs
  U /etc/rc.d/natd
  U /etc/rc.d/netif
  U /etc/rc.d/netoptions
  U /etc/rc.d/netwait
  U /etc/rc.d/newsyslog
  U /etc/rc.d/nfscbd
  U /etc/rc.d/nfsclient
  U /etc/rc.d/nfsd
  U /etc/rc.d/nfsuserd
  U /etc/rc.d/nisdomain
  U /etc/rc.d/nscd
  U /etc/rc.d/ntpd
  U /etc/rc.d/ntpdate
  U /etc/rc.d/opensm
  U /etc/rc.d/os-release
  U /etc/rc.d/othermta
  U /etc/rc.d/pf
  U /etc/rc.d/pflog
  U /etc/rc.d/pfsync
  U /etc/rc.d/power_profile
  U /etc/rc.d/powerd
  U /etc/rc.d/ppp
  U /etc/rc.d/pppoed
  U /etc/rc.d/pwcheck
  U /etc/rc.d/quota
  U /etc/rc.d/random
  U /etc/rc.d/rarpd
  U /etc/rc.d/rctl
  U /etc/rc.d/resolv
  U /etc/rc.d/rfcomm_pppd_server
  U /etc/rc.d/root
  U /etc/rc.d/route6d
  U /etc/rc.d/routed
  U /etc/rc.d/routing
  U /etc/rc.d/rpcbind
  U /etc/rc.d/rtadvd
  U /etc/rc.d/rtsold
  U /etc/rc.d/rwho
  U /etc/rc.d/savecore
  U /etc/rc.d/sdpd
  U /etc/rc.d/securelevel
  U /etc/rc.d/sendmail
  U /etc/rc.d/serial
  U /etc/rc.d/sppp
  U /etc/rc.d/sshd
  U /etc/rc.d/statd
  U /etc/rc.d/static_arp
  U /etc/rc.d/static_ndp
  U /etc/rc.d/stf
  U /etc/rc.d/swap
  U /etc/rc.d/swaplate
  U /etc/rc.d/syscons
  U /etc/rc.d/sysctl
  U /etc/rc.d/syslogd
  U /etc/rc.d/sysvipc
  U /etc/rc.d/tmp
  U /etc/rc.d/ubthidhci
  U /etc/rc.d/ugidfw
  U /etc/rc.d/utx
  U /etc/rc.d/var
  U /etc/rc.d/virecover
  U /etc/rc.d/watchdogd
  U /etc/rc.d/wpa_supplicant
  U /etc/rc.d/ypbind
  U /etc/rc.d/ypldap
  U /etc/rc.d/yppasswdd
  U /etc/rc.d/ypserv
  U /etc/rc.d/ypset
  U /etc/rc.d/ypupdated
  U /etc/rc.d/ypxfrd
  U /etc/rc.d/zfs
  U /etc/rc.d/zfsbe
  U /etc/rc.d/zfsd
  U /etc/rc.d/zvol
  U /etc/rc.firewall
  U /etc/rc.initdiskless
  U /etc/rc.resume
  U /etc/rc.sendmail
  U /etc/rc.shutdown
  U /etc/rc.subr
  U /etc/rc.suspend
  U /etc/regdomain.xml
  U /etc/remote
  U /etc/rpc
  U /etc/security/audit_class
  U /etc/security/audit_control
  U /etc/security/audit_event
  U /etc/security/audit_user
  U /etc/security/audit_warn
  U /etc/services
  M /etc/shells
  U /etc/snmpd.config
  U /etc/ssh/ssh_config
  U /etc/ssh/sshd_config
  U /etc/ssl/openssl.cnf
  U /etc/sysctl.conf
  M /etc/syslog.conf
  U /etc/syslog.d/ftp.conf
  U /etc/syslog.d/lpr.conf
  U /etc/syslog.d/ppp.conf
  U /etc/termcap.small
  U /etc/ttys
  A /etc/kyua/kyua.conf
  A /etc/motd.template
  A /etc/periodic/daily/221.backup-gpart
  A /etc/periodic/daily/222.backup-gmirror
  A /etc/periodic/daily/223.backup-zfs
  A /etc/rc.d/zpool
Warnings:
  Modified regular file remains: /etc/motd
pkg: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	pkg: 1.16.3

Number of packages to be removed: 1

The operation will free 29 MiB.
[r720-02-pg01.int.unixathome.org] [1/1] Deinstalling pkg-1.16.3...
[r720-02-pg01.int.unixathome.org] [1/1] Deleting files for pkg-1.16.3: 100%
Bootstrapping pkg from pkg+http://fedex.int.unixathome.org/packages/122amd64-default-pg13/, please wait...
Verifying signature with public key /etc/ssl/slocum.unixathome.org.cert... done
pkg-static: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
[r720-02-pg01.int.unixathome.org] Installing pkg-1.16.3...
pkg-static: wrong architecture: FreeBSD:12:amd64 instead of FreeBSD:13:amd64

Failed to install the following 1 package(s): /tmp//pkg.txz.pqaMyv

Upgrade cancelled: reverting changes and cleaning up.
[dvl@r720-02:~/src/mkjail] $ 
```

**Comment by dlangille** [comment]
long pause there while my FreeBSD 13.x repos were built.

**Comment by dlangille** [comment]
Success.

```
[dvl@r720-02:~/src/mkjail] $ sudo ./src/bin/mkjail upgrade -a -v 13.0-RELEASE
Upgrading pg01 jail from 12.2-RELEASE to 13.0-RELEASE...

  D /etc/amd.map
  D /etc/newsyslog.conf.d/amd.conf
  D /etc/rc.d/amd

[snip]

Installing updates...Scanning /jails/nginx01/usr/share/certs/blacklisted for certificates...
Scanning /jails/nginx01/usr/share/certs/trusted for certificates...
Scanning /jails/nginx01/usr/local/share/certs for certificates...
 done.
[dvl@r720-02:~/src/mkjail] $ 
```
