### PR TITLE
Sanity check configuration and add JAILDATASET option

### LINKED ISSUE #18: create fails if JAILROOT != /jails
https://github.com/mkjail/mkjail/blob/79b4c0316816823aa137f93706d5f794a50eb4fd/src/share/mkjail/create.sh#L83-L86

If `JAILROOT` isn't set to `/jails` create will fail as the dataset path is hardcoded.

### PR DESCRIPTION
**Pull request by fyfe**
* Ensure the required settings are configured in `mkjail.conf` and that
  they make sense before we run wild with the `zfs` command.

* Added a `JAILDATASET` option for setups where the jail dataset name
  doesn't match the mount point name, for example:

```
NAME                MOUNTPOINT
zroot/jails         /usr/local/jails
```

The above example would require the following mkjail.conf:

```bash
ZPOOL="zroot"
JAILDATASET="jails"
JAILROOT="/usr/local/jails"
```

* Fix #18 and remove the hardcoded references to the jail dataset.

* Created `lib.sh` to hold reusable functions.

### CODE REVIEW

**Comment by fyfe** [comment]
Checking `JAILROOT` is set before we start will also make me less twitchy about this:

https://github.com/mkjail/mkjail/blob/master/src/share/mkjail/upgrade.sh#L52

**Comment by dlangille** [comment]
I need a working `bhyve` installation first.  I'm working on that tonight.

File: src/share/mkjail/create.sh [hunk 1]
```diff
@@ -80,10 +80,9 @@ if [ x"${fflag}" = x1 ] && [ ! -d /var/db/mkjail/flavours/${FLAVOUR} ]; then
 fi
 
 # Create the ZFS filesystem
-echo "Creating ${ZPOOL}/jails/${JAILNAME}..."
-zfs create -p -o mountpoint=/jails ${ZPOOL}/jails
-zfs create -p ${ZPOOL}/jails/${JAILNAME}
-zfs set mkjail:version=${VERSION} ${ZPOOL}/jails/${JAILNAME}
+echo "Creating ${ZPOOL}${JAILDATASET}/${JAILNAME}..."
+zfs create "${ZPOOL}${JAILDATASET}/${JAILNAME}"
```
Comment (dlangille) [inline src/share/mkjail/create.sh]: Why drop the `-p` and `-o` options?

File: src/bin/mkjail [hunk 2]
```diff
@@ -51,6 +56,75 @@ HELP
...
+            echo "NOT_EXIST"
+    )
+    case "$ds_mnt" in
+        "NOT_EXIST")
+            echo "Jail dataset $ZPOOL/$JAILDATASET not found." >&2
+                    cat >&2 << EOM
+
+If this is your first time using mkjail you must first create a dataset for your jails:
+
+zfs create -o mountpoint="$JAILROOT" "$ZPOOL/$JAILDATASET"
```
Comment (dlangille) [inline src/bin/mkjail:104]: This asks the user to create the filesystem, but line 80 of `create.sh` will do this

File: src/share/mkjail/create.sh [hunk 3]
```diff
@@ -80,10 +80,9 @@ if [ x"${fflag}" = x1 ] && [ ! -d /var/db/mkjail/flavours/${FLAVOUR} ]; then
...
+zfs set mkjail:version="${VERSION}" "${ZPOOL}${JAILDATASET}/${JAILNAME}"
```
Comment (dlangille) [inline src/share/mkjail/create.sh]: I think `VERSION` is in quotes to allow greater flexibility in version names.

**Review by dlangille — APPROVED** [review]

File: src/bin/mkjail (hunk 2 above)
Comment (fyfe) [reply src/bin/mkjail]: I had previously removed the first `zfs create` from `create.sh`. I've added it back and moved it into an `_init` function for anything that needs created/checked before the script starts doing anything. This should give an error sooner if the config is wrong rather than waiting until after it's downloaded the FreeBSD release.

File: src/share/mkjail/create.sh (hunk 3 above)
Comment (fyfe) [reply src/share/mkjail/create.sh]: I added the quotes 😀

File: src/share/mkjail/create.sh (hunk 1 above)
Comment (fyfe) [reply src/share/mkjail/create.sh]: I've moved the first create command into the `_init()` function, see my comment below.

For the second create command I removed the `-p` option because if the parent dataset doesn't exist it means the first create command failed and the script should be exiting.

**Comment by fyfe** [comment]
I've added a `lib.sh` file to hold common functions all the scripts can use. The functions in there currently can also be used for the `mkjail` ZFS dataset.

Unless there are any other issues I'll squash these commits into one and it should be ready to pull.

**Comment by dlangille** [comment]
I've not forgotten this.

**Comment by dlangille** [comment]
With:

```
# Set your zpool name
ZPOOL="zroot"

JAILDATASET="zroot"

# Set jail root filesystem path
JAILROOT="/jails"
```

I'm getting:

```
[dvl@mkjail ~/src/mkjail/src]$ sudo bin/mkjail create -j test02 -a amd64 -v 12.2-RELEASE
cannot open 'zroot/zroot': dataset does not exist
Creating dataset zroot/zroot
Creating zroot/zroot/test02...
Extracting base into /jails/test02...
Updating test02 jail...
...
```

**Comment by dlangille** [comment]
With this default configuration:

```
[dvl@mkjail ~/src/mkjail/src]$ cat etc/mkjail.conf
# mkjail config file

# Set your zpool name
ZPOOL="zroot"

# Set the jail dataset name (without the zpool name)
# DEFAULT: jails
JAILDATASET="jails"

# Set jail root filesystem path
# DEFAULT: /jails
JAILROOT="/jails"

# Sets you want extracted into new jail
# options include: base-dbg, base, kernel-dbg, kernel, lib32-dbg, lib32, ports, src tests
# DEFAULT: base
SETS="base"
[dvl@mkjail ~/src/mkjail/src]$ 
```

I get:

```
[dvl@mkjail ~/src/mkjail/src]$ sudo bin/mkjail create -j test03 -a amd64 -v 12.2-RELEASE
Creating zroot/jails/test03...
Extracting base into /jails/test03...
Updating test03 jail...

src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 12.2-RELEASE from update1.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.
The following files will be removed as part of updating to
12.2-RELEASE-p9:
/etc/ssl/certs/2c543cd1.0
...
```

Which creates:

```
zroot/jails                 909M  13.3G    96K  /jails
zroot/jails/test01          455M  13.3G   455M  /jails/test01
zroot/jails/test03          455M  13.3G   455M  /jails/test03
```

**Comment by dlangille** [comment]
I note that the newly created jail did not get patched:

```
root@test04:/ # uname -a
FreeBSD test04 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64
root@test04:/ # 
```

**Comment by dlangille** [comment]
Trying a FreeBSD 11.4 jail

```
[dvl@mkjail ~/src/mkjail/src]$ sudo bin/mkjail create -j test05 -a amd64 -v 11.4-RELEASE
Release 11.4-RELEASE does not exist. Attempting to fetch...
Fetching release manifest...
MANIFEST                                              1157  B 3871 kBps    00s
Fetching release tarballs...
base.txz                                               125 MB   12 MBps    11s
src.txz                                                154 MB   12 MBps    13s
base.txz: sha256 verified
src.txz: sha256 verified
...

root@test05:/ # freebsd-version -ur
12.2-RELEASE-p7
11.4-RELEASE-p12
```
